package com.example.witcherbestiary.carouselSlot.description

import com.example.witcherbestiary.carouselSlot.view.description.CarouselSlotViewDescription
import com.example.bloc.description.ComponentDescription

interface CarouselSlotDescription : ComponentDescription<CarouselSlotViewDescription>